Footer da pagina home
WagnerTerry/MercadoJuca pull request #1
Opened 2023-02-14 20:02 UTC by MiguelDaSilvaGomes

2023-02-14 21:01 UTC, WagnerTerry requested changes

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.jsx
> +const footer = () => {
nome dos componentes tem que ser com letra Maiuscula

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.jsx
> +export default footer
aqui a mesma coisa

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.jsx
> +   <div id='IMG'>
evitar de colocar nome de elemento para id ou className

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.jsx
> +   <img className='Img1' src='../src/assets/Instagram.png '/>
evitar nome de classe com numeros subsequentes img1, img2 etc...

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.scss
> +.button{
button é uma tag, então voce nao precisa colocar ponto, só para classes

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.scss
> +.input{
mesma coisa aqui sobre ponto

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.scss
> +.divFooter{
aninhar todos os elementos dentro de uma div pai

2023-02-14 21:01 UTC, WagnerTerry commented on src/components/Footer.scss
> +  position: relative;
mudar esse codigo para flexbox

2023-02-14 21:01 UTC, WagnerTerry commented on src/App.scss
> +
pode remover o conteudo de sass se nao tiver relacionado ao App.jsx

2023-02-16 00:03 UTC, SamaraRib requested changes
Troca a cor de fundo e a fonte também pra ficar como ta no Figma

2023-02-27 20:00 UTC, WagnerTerry approved these changes

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.jsx
> +    <div className='Inscrever'>
nomes de classes, coloque tudo com letra minuscula

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.scss
> +
aqui ainda nao esta no padrão do sass

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.jsx
> +       <div id="imagens-do-footer-home">
evitar nomes grandes, ser especifico na hora de criar a className ou id

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.scss
> +     *{
esse símbolo pode ser colocado na primeira linha

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.jsx
> +              <input placeholder='Digite seu melhor email' className='input'  type="text" />
remover essa classe

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.jsx
> +              <button className='button' >Inscrever</button>
mesma coisa aqui

2023-02-27 20:00 UTC, WagnerTerry commented on src/components/Footer.scss
> +   @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
remover import

2023-02-27 22:42 UTC, SamaraRib approved these changes

2023-02-27 22:49 UTC, merged